apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::846749788810:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-3VZazDaneGWU
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::846749788810:user/suresh
      username: suresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::846749788810:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-29T04:52:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1224"
  uid: 0159190e-153c-42d9-8423-fd99f5a51d22

