apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::160885265516:role/eksctl-roboshop-addon-iamserviceaccount-robos-Role1-U9PU6RsXqivj
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: roboshop-secret-reader
  namespace: roboshop